### ISSUE TITLE
模组依赖管理

### ISSUE THREAD

**Issue by YangAoLib** [Lake1059/SMUI-2023#1]
通过管理配置文件的方式对模组进行管理。
在模组中只需要写入或选择顶层模组，其相关的依赖模组可以被自动包含。

这样可以减少因为依赖模组管理不当，出现的模组管理问题。

**Comment by Lake1059** [comment]
SMUI 的核心设计与这种方式不兼容，项的概念相当于套一层壳，此时一个项已经不能代表一个模组。SMUI 的设计建立在“支持全部类型的安装方式”之上，这也是 SMUI 诞生的意义，因此传统方式里的设计永远不会在 SMUI 上实现。

其次关于模组列表配置文件的设计，在六代中会有类似的东西。
