### ISSUE TITLE
检查更新时步骤二所有内容显示为省略号

### ISSUE THREAD

**Issue by emptylight370** [Lake1059/SMUI-2023#2]
在检查更新时右侧的所有内容显示为省略号，可能是显示的宽度不够导致。
![PixPin_2024-10-13_21-46-12](https://github.com/user-attachments/assets/212336b9-6dfe-416b-aa8f-2a86aee2ff66)
见过有能显示出单字的，也见过唯一一次能全部显示的（仅单个mod时候），不知道具体是什么情况，不过大部分情况下都是显示一排省略号。

系统：Windows11
缩放：125%
SMUI：6.6.3

**Comment by Lake1059** [comment]
离线教程已提醒，调度设计问题，动一下窗口位置或者调整一下尺寸即可，不会再解决

**Comment by emptylight370** [comment]
理解文档了，感谢解答
